#!/usr/bin/env sh

echo "Ejecutando verificaciones previas al push..."

echo "Ejecutando tests..."
pnpm test

if [ $? -eq 0 ]; then
    echo "Tests exitosos. Ejecutando build..."
    pnpm build
else
    echo "Tests fallidos. Push cancelado."
    exit 1
fi

if [ $? -ne 0 ]; then
    echo "Build fallido. Push cancelado."
    exit 1
fi

echo "Todas las verificaciones completadas. Procediendo con el push..."